### ISSUE TITLE
PermissionVoter should return ACCESS_ABSTAIN if subject is not managed

### ISSUE THREAD

**Issue by ste93cry** [fxpio/fxp-security#3]
While the `PermissionVoter` voter checks whether a subject is supported by ensuring that the attribute has the correct `perm_` prefix and the subject is an object, it should also check also that the subject itself is managed by the permission manager, otherwise if any object that should not be protected is passed to the voter the result will be `ACCESS_DENIED` instead of the expected `ACCESS_ABSTAIN`.

**Comment by francoispluchino** [comment]
To retrieve the `ACCESS_DENIED` value and not the `ACCESS_ABSTAIN` value, the object class must be managed by the permission manager.

**Comment by ste93cry** [comment]
Exactly, and this does not work. If the object class is not managed by the permission manager `ACCESS_DENIED` is returned instead of the expected `ACCESS_ABSTAIN`

**Comment by francoispluchino** [comment]
Sorry, I understood the opposite ... Indeed, The `PermissionVoter` doesn't verify if the subject is managed by the permission manager in the `supports` method (see the [code](https://github.com/fxpio/fxp-security/blob/master/Authorization/Voter/PermissionVoter.php#L83)).
