### ISSUE TITLE
Documantation about Using Organizations

### ISSUE THREAD

**Issue by megadruck** [fxpio/fxp-security#4]
hello

can you send give me an detaild documentation about using Using Organizations ?
How to create an organization and how to add an user to it.
How does it work in combination with roles and permissions ?

thy in advance

**Comment by francoispluchino** [comment]
You can find the most [complete documentation](https://github.com/fxpio/fxp-security-bundle/blob/master/Resources/doc/index.md) of the new version in [Fxp Security Bundle](https://github.com/fxpio/fxp-security-bundle). There is now the documentation concerning the [management of organizations](https://github.com/fxpio/fxp-security-bundle/blob/master/Resources/doc/organizations.md).
